config/routes.rb
Rails.application.routes.draw do
  root to: 'site#index'

  resources :restaurants
  resource :ratings, only: :update

  devise_for :users

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user

  validates :score, inclusion: { in: (0..5), message: "Ratings are 0 to 5" }
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :ratings, dependent: :destroy

  validates :title, presence: true
  validates :address, presence: true

  def visit!
    update(last_visited: Time.zone.now)
  end

  def self.last_visited
    where("last_visited is not null").order("last_visited").last
  end

  def average_rating
    if self.ratings.size > 0
      self.ratings.average(:score).round(1)
    else
      0
    end
  end

  # Returns a restaurant that is weighted for not being visited for
  # a while and being well rated. The idea is to avoid visiting
  # low-rated restaurants until they have not been visited for a while
  def self.whats_for_lunch
    half_of_restaurants = self.count / 2
    best_rated_amount = (half_of_restaurants / 1.5).round(0)
    restaurants = order("last_visited").first(half_of_restaurants)
    best_rated = restaurants.sort_by(&:average_rating).reverse.first(best_rated_amount)
    return best_rated.sample
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ratings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find_by_id params["id"]
  end

  def edit
    @restaurant = Restaurant.find_by_id params["id"]
  end

  def update
    @restaurant = Restaurant.find_by_id params["id"]
    if @restaurant.update_attributes(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant = Restaurant.find_by_id params["id"]
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:title, :description, :phone_number)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @restaurant = Restaurant.whats_for_lunch
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lunchly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="wrapper">
    <%= yield %>

    <footer id="footer">
      <ul class="copyright">
        <li>&copy; Robert Qualls</li>
        <li>Design: <a href="http://robertqualls.com">RQ</a> and <a href="http://html5up.net">HTML5 UP</a></li>
      </ul>
    </footer>
  </div>

</body>
</html>

app/views/restaurants/edit.html.erb
<section id="main">
  <header>
    <span class="avatar"><%= image_tag('thai-food.jpg') %></span>
  </header>

  <h2>Edit Restaurant</h2>
  <%= form_for @restaurant do |f| %>
    <%= f.label :title, class: "field" %>
    <%= f.text_field :title, class: "field" %>
    <%= f.label :description, class: "field" %>
    <%= f.text_area :description, class: "field" %>
    <%= f.label :phone_numner, class: "field" %>
    <%= f.text_field :phone_number, class: "field" %>
    <%= f.submit 'Update', class: "field" %>
  <% end %>
  <!-- <form method="post" action="#"> -->
  <!--   <div class="field"> -->
  <!--     <input type="text" name="name" id="name" placeholder="Name" /> -->
  <!--   </div> -->
  <!--   <div class="field"> -->
  <!--     <input type="text" name="description" id="description" placeholder="Description" /> -->
  <!--   </div> -->
    <!-- <div class="field"> -->
    <!--   <div class="select&#45;wrapper"> -->
    <!--     <select name="department" id="department"> -->
    <!--       <option value="">Department</option> -->
    <!--       <option value="sales">Sales</option> -->
    <!--       <option value="tech">Tech Support</option> -->
    <!--       <option value="null">/dev/null</option> -->
    <!--     </select> -->
    <!--   </div> -->
    <!-- </div> -->
  <!--   <div class="field"> -->
  <!--     <textarea name="message" id="message" placeholder="Message" rows="4"></textarea> -->
  <!--   </div> -->
  <!--   <div class="field"> -->
  <!--     <input type="checkbox" id="human" name="human" /><label for="human">I'm a human</label> -->
  <!--   </div> -->
  <!--   <div class="field"> -->
  <!--     <label>But are you a robot?</label> -->
  <!--     <input type="radio" id="robot_yes" name="robot" /><label for="robot_yes">Yes</label> -->
  <!--     <input type="radio" id="robot_no" name="robot" /><label for="robot_no">No</label> -->
  <!--   </div> -->
  <!--   <ul class="actions"> -->
  <!--     <li><a href="#" class="button">Get Started</a></li> -->
  <!--   </ul> -->
  <!-- </form> -->
  <footer>
    <ul class="icons">
      <li><a href="/" class="fa-home">Home</a></li>
      <li><%= link_to 'Destroy',  @restaurant,  method: :delete, data: { confirm: 'Are you sure?' }, class: "fa-trash"  %></li>
    </ul>
  </footer>
</section>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul class="icons">
  <li><a href="/" class="fa-home">Home</a></li>
</ul>

<% @restaurants.each do |restaurant| %>
  <p>
  <a href="<%= restaurant_path(restaurant) %>"><%= restaurant.title %></a>
  <span>Rating: <%= restaurant.average_rating %></span>
  </p>
<% end %>

app/views/restaurants/show.html.erb
<section id="main" class="nopacity">
  <header>
    <span class="avatar"><%= image_tag('thai-food.jpg') %></span>
    <h1><%= @restaurant.title %></h1>

    <% unless @restaurant.description.blank? %>
      <p><%= @restaurant.description %></p>
    <% end %>

    <p><%= @restaurant.address %></p>

    <% unless @restaurant.phone_number.blank? %>
      <p><%= @restaurant.phone_number %></p>
    <% end %>
  </header>

  <footer>
    <div id="rating" class="center"></div>
    <ul class="icons">
      <li><a href="/" class="fa-home">Home</a></li>
      <li><a href="/restaurants" class="fa-list">Restaurants</a></li>
      <li><%= link_to 'Edit', edit_restaurant_path(@restaurant), class: "fa-edit" %></li>
    </ul>
  </footer>
</section>

<script type="text/javascript">
  $(document).on('ready page:load', function() {
    $(".nopacity").animate({opacity: 0.95}, 100);

    $("#rating").rateYo({
      starWidth: "50px",
      rating: <%= @restaurant.average_rating %>,
      ratedFill: "#F0CE4E",
      readOnly: true
    });
  });
</script>

app/views/site/index.html.erb
<section id="main" class="nopacity">
  <header>
    <span class="avatar"><%= image_tag('thai-food.jpg')%></span>
    <h3>Today's lunch is</h3>
    <h1><%= link_to @restaurant.title, @restaurant %></h1>
    <p>The last time we visited was <%= time_ago_in_words(@restaurant.last_visited) %> ago</p>
  </header>

  <footer>
    <div id="rating" class="center"></div> 

    <% if user_signed_in? %>
      <ul class="icons">
        <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "fa-sign-out" %></li>
      </ul>
    <% end %>
  </footer>

</section>

<script type="text/javascript">
  $(document).on('ready page:load', function() {
    $(".nopacity").animate({opacity: 0.95}, 150);

    $("#rating").rateYo({
      starWidth: "50px",
      rating: <%= @restaurant.average_rating %>,
      ratedFill: "#F0CE4E",
      readOnly: true
    });
  });
</script>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>